### ISSUE TITLE
Terraform v0.12 now requires consistent usage of argument syntax for arguments and nested block syntax for nested blocks.

### ISSUE THREAD

**Issue by arekgoral** [marcransome/terraform-aws-vpc-public-private-nat#1]
https://github.com/marcransome/terraform-aws-vpc-public-private-nat/blob/4ec20a18a4d1dec924414918d1efdd29f407eeaf/main.tf#

tags {

in Terraform 0.12 needs changed to 

tags = {

https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks

**Comment by marcransome** [comment]
Fixed in https://github.com/marcransome/terraform-aws-vpc-public-private-nat/commit/5aaa1316a4963c2ddbe38fd14c7055422239d883 and released as version [1.0.0](https://github.com/marcransome/terraform-aws-vpc-public-private-nat/releases/tag/1.0.0).
